List<String> getLyrics() {
  return [
    " Si te vas, yo quiero saber si tú te vas",
    "Mami, cuando tú quieras",
    "Cuando tú quieras, yeah, yeah",
    "Vete, eh eh eh",
    "Nadie te está aguantando",
    "y la puerta está abierta, eh",
    "No te preocupes por nosotros dos,",
    "nuestra historia ya está muerta",
    "Espero que seas feliz",
    "y que te diviertas, eh",
    "Pero pa' acá no vuelvas, no no no no",
    "Vete, eh eh eh",
    "Nadie te está aguantando",
    "y la puerta está abierta, eh",
    "No te preocupes por nosotros dos,",
    "nuestra historia ya está muerta",
    "Espero que seas feliz",
    "y que te diviertas, eh",
    "Pero pa' acá no vuelvas, no no no no",
    "Ey",
    "Dime qué esperas",
    "Baby, te quiero, pero afuera",
    "Eres alguien por dentro y otra por fuera",
    "Y ya no siento nada cuando te encuera'",
    "Dame, dame banda, eh",
    "En mi corazón ya tú no eres la que manda",
    "Se acabó, por ti ya no siento nada",
    "De nuestra serie ya no salen temporadas",
    "Así que vete lejo',",
    "dile al diablo que te envíe el pin",
    "Hace tiempo que no somos un team",
    "Pa'l carajo nuestro aniversario y San Valentín",
    "Ya no hay más Christian Lou",
    "ni los trajes en satín",
    "Síguelo, que está verde, eh",
    "Que tienes la culpa es lo que te muerde",
    "Quédate con el perro, pa' que de mí te acuerdes",
    "Y piense' en to' lo que te pierde'",
    "Pero te deseo suerte, ahora soy más fuerte",
    "Gracias a to' lo que me hiciste, eh",
    "Tú nunca me quisiste, eh",
    "No sé por qué me insiste'",
    "Pero te deseo suerte, ahora soy más fuerte",
    "Gracias a to' lo que me hiciste, eh",
    "Tú nunca me quisiste, eh",
    "No sé por qué me insiste'",
    "Vete, eh eh eh",
    "Nadie te está aguantando",
    "y la puerta está abierta, eh",
    "No te preocupes por nosotros dos,",
    "nuestra historia ya está muerta",
    "Espero que seas feliz y que te diviertas, eh",
    "Pero pa' acá no vuelvas, no no no no",
    "Vete, eh eh eh",
    "Nadie te está aguantando",
    "y la puerta está abierta, eh",
    "No te preocupes por nosotros dos,",
    "nuestra historia ya está muerta",
    "Espero que seas feliz y que te diviertas, eh",
    "Pero pa' acá no vuelvas, no no no no",
  ];
}
